# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/IDE/Vivado/HardwareDesign/step_into_mips-lab_4/lab_4/lab_4/lab_4.srcs/sources_1/ip/inst_mem_dual/inst_mem_dual.xci
# IP: The module: 'inst_mem_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/IDE/Vivado/HardwareDesign/step_into_mips-lab_4/lab_4/lab_4/lab_4.srcs/sources_1/ip/inst_mem_dual/inst_mem_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem_dual'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/IDE/Vivado/HardwareDesign/step_into_mips-lab_4/lab_4/lab_4/lab_4.srcs/sources_1/ip/inst_mem_dual/inst_mem_dual.xci
# IP: The module: 'inst_mem_dual' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/IDE/Vivado/HardwareDesign/step_into_mips-lab_4/lab_4/lab_4/lab_4.srcs/sources_1/ip/inst_mem_dual/inst_mem_dual_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_mem_dual'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
